pipelines:
  default:
    - step:
        image: node/lts
        name: test
        script: 
          - npm install -g truffle
          - npm install -g coveralls
          - npm install
          - npm run test
          - npm run coverage
